#!/usr/bin/env bash
ssh root@localhost -p 10022  -o ConnectTimeout=5 "./execute_return_exitcode.sh '$@'" | tee output.log | grep -v SSH_REMOTE_EXIT_CODE=
exit_code=$?
if [ $exit_code != 0 ]; then
    exit $exit_code
fi
res=`tail -n1 output.log`
exit_code="${res##*SSH_REMOTE_EXIT_CODE=}"
if [[ ! -n "$exit_code" ]]; then
    exit_code=127
fi
exit $exit_code
